interfaces_vlans:
  # - name: Vlan4094
  #   description: MLAG-PEER
  #   mode: vlan_l3_ipv4
  #   mtu: 9214
  #   ipv4_address: 192.168.40.94/31
  - name: Vlan11
    description: FLOOR_11_DATA
    mode: vlan_l3_ipv4
    mtu: 9214
    ipv4_address: 10.11.0.2/24
    virtual_router: 10.11.0.1
interfaces_physical:
  ########################################
  # LEAVE THIS COMMENTED OUT FOR VAGRANT #
  ########################################
  # - name: Management1
  #   vrf: MGMT
  #   ipv4_address: "{{ ansible_host }}/24"
  #   mode: management
  - name: Ethernet1
    speed: 10000full
    mode: l3_ipv4
    description: "aggregation01_spine02"
    ipv4_address: 10.102.1.1/31
  - name: Ethernet2
    speed: 10000full
    mode: l3_ipv4
    description: "aggregation02_spine02"
    ipv4_address: 10.202.1.1/31
  - name: Ethernet3
    speed: 10000full
    mode: l3_ipv4
    description: "spine01_leaf01"
    ipv4_address: 10.255.11.0/31
  - name: Ethernet4
    speed: 10000full
    mode: l3_ipv4
    description: "spine01_leaf02"
    ipv4_address: 10.255.12.0/31
  - name: Ethernet5
    speed: 10000full
    mode: l3_ipv4
    description: "spine01_leaf03"
    ipv4_address: 10.255.13.0/31
  - name: Ethernet6
    speed: 10000full
    mode: l3_ipv4
    description: "spine01_leaf04"
    ipv4_address: 10.255.14.0/31
