# DATA MODEL BUILT OFF OF JUNIPER
interfaces:
  physical_single:
# START OF PHYSICAL INTERFACES #
  ########################################
  # LEAVE THIS COMMENTED OUT FOR VAGRANT #
  ########################################
    # - name: Management1
    #   description: management
    #   speed: 10000full
    #   subinterface:
    #     - unit: 0
    #       vrf: MGMT
    #       family:
    #         mode: inet
    #         inet: dhcp
    - name: Ethernet1
      description: aggregation01_spine02
      speed: 10000full
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.102.1.1/31
    - name: Ethernet2
      description: aggregation02_spine02
      speed: 10000full
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.202.1.1/31
    - name: Ethernet3
      description: spine02_leaf01
      speed: 10000full
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.255.11.2/31
    - name: Ethernet4
      description: spine02_leaf02
      speed: 10000full
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.255.12.2/31
    - name: Ethernet5
      description: spine02_leaf03
      speed: 10000full
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.255.13.2/31
    - name: Ethernet6
      description: spine02_leaf04
      speed: 10000full
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.255.14.2/31
    # - name: Ethernet7
    #   description: spine01_leaf04
    #   speed: 10000full
    #   subinterface:
    #     - unit: 0
    #       family:
    #         mode: ethernet-switching
    #         vlans: vlan_0010
    #         type: access
    # - name: Ethernet8
    #   description: TRUNK_TO_RACK
    #   subinterface:
    #   - unit: 0
    #     channel_group:
    #       id: 11
    #       mode: trunk
    #     mlag: True
    #     stp_portfast: True
    #     stp_bpduguard: True
    #     family:
    #       mode: ethernet-switching
    #       vlans: vlan_0010 vlan_0020 vlan_0030 vlan_0040 vlan_0050
    #       type: trunk

# END OF PHYSICAL INTERFACES #
# START OF VIRTUAL INTERFACES #
    - name: lo0
      description: loopback0
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 172.16.20.2/32
    - name: svi
      subinterface:
        - unit: 11
          description: FLOOR_11_DATA
          family:
            mode: inet
            inet: 10.11.0.3/24
            virtual_router: 10.11.0.1
