ospf:
  area:
    - id: 0.0.0.0
      networks:
        - prefix: 192.168.255.0/24
          area: 0.0.0.0
      interface:
        - iface: Et3
          type: p2p
        - iface: Et4
          type: p2p
        - iface: Et5
          type: p2p
        - iface: Et6
          type: p2p
  export:
    - policy: REDISTRIBUTE-DIRECT
      protocol: local
