syslog:
  archive_configuration: archive size 10m files 10
  user:
    - name: '*'
      facility: any
      severity: emergency
  host:
    - ipv4_address: 10.30.2.1
      facility: any
      severity: any
      source_address: 10.30.0.2
    - ipv4_address: 10.30.2.2
      facility: any
      severity: error
      source_address: 10.30.0.2
  file:
    - file_name: messages
      facility: any
      severity: notice
      authorization: info
      priority: explicit-priority
    - file_name: default-log-messages
      facility: any
      severity: info
      options:
        - structured-data
        - match "(requested 'commit' operation)|(copying configuration to juniper.save)|(commit complete)|ifAdminStatus|(FRU power)|(FRU removal)|(FRU insertion)|(link UP)|transitioned|Transferred|transfer-file|(license add)|(license delete)|(package -X update)|(package -X delete)|(FRU Online)|(FRU Offline)|(plugged in)|(unplugged)|GRES"
https://github.com/packetferret/junos_ansible_lab/blob/master/host_vars/juniper-ex-01/system.yml
