bgp:
  autonomous_system: 65000
  router_id: 192.168.79.2
  maximum_paths: 32
  distance:
    external: 20
    internal: 200
    local: 200
  peer_group:
    - name: spine
      neighbor:
        - 10.201.1.1
        - 10.202.1.1
      autonomous_system: 6684673
      activate: True
      default_originate: True
      policy_in: BGP_PERMIT_ONLY_DEFAULT_ROUTE
      policy_out: BGP_DISTRIBUTION
      password: CUMULUS_ARISTA
      description: AGGREGATION_TO_SPINE
