interfaces:
  - name: lo
    address: "10.201.1.0/31"
    loopback: True
  - name: eth0
    address: "dhcp"
  - name: swp1
    address: "10.201.1.0/31"
  - name: swp2
    address: "10.202.1.0/31"
  - name: swp3
    address: "192.168.255.1/31"
