# DATA MODEL BUILT OFF OF JUNIPER
interfaces:
  physical_single:
# START OF VIRTUAL INTERFACES #
    - name: lo
      description: loopback0
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.201.1.0/32
# START OF PHYSICAL INTERFACES #
    - name: eth0
      description: management
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: dhcp
    - name: swp1
      description: aggregation01_spine01
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.201.1.0/31
    - name: swp2
      description: aggregation01_spine02
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 10.202.1.0/31
    - name: swp3
      description: aggregation01_spine01
      subinterface:
        - unit: 0
          family:
            mode: inet
            inet: 192.168.255.1/31
# END OF PHYSICAL INTERFACES #
