ospf:
  area:
    - id: 0.0.0.0
      networks:
        - prefix: 192.168.255.0/24
          area: 0.0.0.0
      interface:
        - iface: Et3
          type: p2p
        - iface: Et4
          type: p2p
        - iface: Et5
          type: p2p
        - iface: Et6
          type: p2p
  export:
    - policy: REDISTRIBUTE-DIRECT
      protocol: connected
# ospf:
#   router_id: 192.168.102.1
#   process_id: "1"
#   networks:
#     - prefix: '10.255.11.0/24'
#       area: 0
#     - prefix: '10.255.12.0/24'
#       area: 0
#     - prefix: '10.255.13.0/24'
#       area: 0
#     - prefix: '10.255.14.0/24'
#       area: 0
