---
  - name: "# CUMULUS - REMOVE DAEMONS FILE IF IT EXISTS #"
    file:
      path: "{{ configuration_directory }}/{{ inventory_hostname }}_daemons.conf"
      state: absent

  - name: "# CUMULUS - BUILD DAEMONS FILE #"
    template:
      src: "daemons.j2"
      dest: "{{ configuration_directory }}/{{ inventory_hostname }}_daemons.conf"

  - name: "# CUMULUS - REMOVE FRR CONFIGURATION FILE IF IT EXISTS #"
    file:
      path: "{{ configuration_directory }}/{{ inventory_hostname }}_frr.conf"
      state: absent

  - name: "# CUMULUS - BUILD FRR CONFIGURATION FILE #"
    template:
      src: "frr.j2"
      dest: "{{ configuration_directory }}/{{ inventory_hostname }}_frr.conf"
