prefix_lists:
  - name: DEFAULT_ROUTE
    lines:
      - id: 10
        action: permit
        prefix: 0.0.0.0/0
  - name: ANY
    lines:
      - id: 5
        action: permit
        prefix: 0.0.0.0/0 le 32
  - name: FLOOR_11
    lines:
      - id: 10
        action: permit
        prefix: 10.11.1.0/24
      - id: 15
        action: permit
        prefix: 10.11.2.0/23
      - id: 20
        action: permit
        prefix: 10.11.4.0/22
      - id: 25
        action: permit
        prefix: 10.11.255.0/24

