---
  - name: '### ARISTA - APPLY CONFIGURATION ###'
    hosts: spine
    connection: local
    gather_facts: False
    tasks:

      - name: "# ARISTA - APPLY CONFIGURATION #"
        eos_config:
          src: "{{ configuration_absolute }}"
          authorize: true
          provider:
            host: "{{ ansible_host }}"
            username: vagrant
            password: vagrant
            transport: cli
