- name: "# ### BUILD FRR CONFIGURATIONS ### #"
  hosts: cumulus
  gather_facts: False
  connection: local
  tasks:

    - name: "# REMOVE DAEMONS FILE IF IT EXISTS #"
      file:
        path: "/tmp/{{ inventory_hostname }}_daemons.conf"
        state: absent

    - name: "# BUILD DAEMONS FILE #"
      template:
        src: "templates/cumulus_daemons.j2"
        dest: "/tmp/{{ inventory_hostname }}_daemons.conf"

    - name: "# REMOVE FRR CONFIGURATION FILE IF IT EXISTS #"
      file:
        path: "/tmp/{{ inventory_hostname }}_frr.conf"
        state: absent

    - name: "# BUILD FRR CONFIGURATION FILE #"
      template:
        src: "templates/cumulus_frr.j2"
        dest: "/tmp/{{ inventory_hostname }}_frr.conf"
