---
  - name: "### JUNOS - APPLY CONFIGURATION ###"
    hosts: leaf
    gather_facts: False
    connection: local
    tasks:
      - name: "# JUNOS - APPLY CONFIGURATION #"
        junos_command:
          provider:
            host: "{{ ansible_ssh_host }}"
            port: 8830
            username: root
            password: Juniper
          commands: show version
