---
  - name: "### JUNOS - APPLY CONFIGURATION ###"
    hosts: leaf
    gather_facts: False
    connection: local
    tasks:
      - name: "# JUNOS - APPLY CONFIGURATION #"
        junos_config:
          provider:
            host: "{{ ansible_ssh_host }}"
            port: "{{ ansible_port }}"
            username: root
            password: Juniper
          src: "{{ configuration_absolute }}"
          src_format: text
          comment: "applied by ansible"
          update: replace
