---
  - name: Apply generated configurations
    hosts: leaf
    connection: local
    gather_facts: no
    vars:

    tasks:
      - name: pushing configuration to device, please wait...
        junos_config:
          src: "{{ configuration_absolute }}"
          src_format: text
          comment: "applied by ansible"
          provider:
            host: "{{ inventory_hostname }}"
            username: vagrant
            password: vagrant
          update: replace
        register: result
