# This task gets all Junos configuration from all devices
- name: Build and deploy configuration
  hosts: aggregation01
  become: True
  tasks:

    - name: "### BUILD INTERFACE CONFIGURATION ###"
      template:
        src: "cumulus_iface.j2"
        dest: "/tmp/{{ inventory_hostname }}.conf"

    - name: "### PUSH CONFIGURATION TO REMOTE HOST ###"
      copy:
        src: "/tmp/{{ inventory_hostname }}.conf"
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644
