aaa:
  group:
    - name: radius_aaa
      servers:
        - destination: 10.255.1.1
          vrf: MGMT
        - destination: 10.255.1.2
          vrf: MGMT
  authentication:
    - aaa authentication login default group radius group radius_aaa local
  accounting:
    - aaa authorization exec default group radius_aaa local none
  authorization:
    - aaa accounting exec default start-stop group radius group radius_aaa
