snmp:
  name: "{{ inventory_hostname }}"
  location: '"Houston, Texas"'
  contact: "Calvin Remsburg"
  community:
    - string: 'public'
      authorization: read-write
      clients:
        - 10.255.0.0/16
        - 10.255.1.0/16
  # trapOptions:
  #   - source-address "{{ ansible_host }}"
  trapGroup:
    - name: trap
      version: v2
      port: 162
      categories:
        - chassis
        - routing
        - authentication
        - link
        - startup
        - services
      targets:
        - 10.255.0.1
