system:
  domain_name: example.com
  domain_search: example.com
  time_zone: America/Chicago
  arp_aging_timer: 5
  auth_order: 'password'
  root_encrypted_password: '$5$AXpsXiSr$J9S.i.up6XjFsVGAIgWtp5xJmMsWHtUF.6K5cMEAi19'
  name_server:
    - 10.255.1.1
    - 10.255.1.2
    - 8.8.8.8
#  radius_server:
#    - ip_address: 10.255.1.1
#      secret: '_INSERT-ENCRYPTED-RADIUS-PASS-HERE_'
#  accounting:
#    events: '[ change-log interactive-commands ]'
#    destination:
#      - type: radius
#        server: 10.255.1.1
#        secret: '_INSERT-ENCRYPTED-RADIUS-PASS-HERE_'
  login:
    message: '==================================================================\n==================================================================\n===             UNAUTHORIZED IP ADDRESS DETECTED               ===\n===               LOGGING AND HONEYPOT ENABLED                 ===\n==================================================================\n=================================================================='
    class:
      - name: SUPER_USER
        idleTimeout: 0
        permissions: all
    user:
      - name: ansible
        uid: 2101
        encryptPass: '$1$cwB59j4k$4bwkQGzyt32awvpYeCoYJ0'
        permissions: SUPER_USER
      - name: ansibletower
        uid: 2102
        encryptPass: '$5$9sxWwCt0$tY7GdqsEHOQslnt6uxtud9eUaw3hWO3tN1how7SgzA2'
        permissions: SUPER_USER
  passwordRequirements: minimum-length 8
  services:
    ftp: True
    ssh:
      - max-sessions-per-connection 4
    netconf: True
    rest:
      http:
        port: 8080
      options:
        - enable-explorer
    # dhcp:
    #   group:
    #     name: TRUSTED
    #     iface: ge-0/0/2.0
  ntp:
    bootserver: 10.255.1.1
    server:
      - ipv4_address: 10.255.1.1
      - ipv4_address: 10.255.1.2

daemon:
  - name: TerminAttr
    string: "exec /usr/bin/TerminAttr -ingestgrpcurl=10.255.1.100:9910 -taillogs -ingestauth=key, -ingestvrf MGMT"
    state: no shutdown

email:
  from_user: "ansible_lab@email.com"
  vrf: "MGMT"
  server: "mail.test.com"

load_interval: "30"

platform: "vEOS"
queue_monitor: "length"

name_server:
  vrf: "MGMT"
  server: "10.255.1.1"

domain_name: "example.com"

ntp:
  source: "Management1"
  server: "10.255.1.1"
  vrf: "MGMT"

aaa_tmp:
  auth: "aaa authorization exec default local"
  root: "no aaa root"
  user:
    - name: cvpadmin
      privilege: 15
      secret: "sha512 $6$i1wYXKTOekzKY648$kTUM2S/KMGh.vgRVYEQZdoDcWJsF4zk.uFIDxdBB.rJjL34Br3hKDJ.NMJSwFYu7nzLlzDCEWIRhCn4DnQHU71"
    - name: ansibletower
      privilege: 15
      secret: "ansible1"
