system:
  domain_name: example.com
  domain_search: example.com
  time_zone: America/Chicago
  arp_aging_timer: 5
  auth_order: 'password'
  root_encrypted_password: '$5$AXpsXiSr$J9S.i.up6XjFsVGAIgWtp5xJmMsWHtUF.6K5cMEAi19'
  name_server:
    - 10.255.1.1
    - 10.255.1.2
    - 8.8.8.8
#  radius_server:
#    - ip_address: 10.255.1.1
#      secret: '_INSERT-ENCRYPTED-RADIUS-PASS-HERE_'
#  accounting:
#    events: '[ change-log interactive-commands ]'
#    destination:
#      - type: radius
#        server: 10.255.1.1
#        secret: '_INSERT-ENCRYPTED-RADIUS-PASS-HERE_'
  login:
    message: '==================================================================\n==================================================================\n===             UNAUTHORIZED IP ADDRESS DETECTED               ===\n===               LOGGING AND HONEYPOT ENABLED                 ===\n==================================================================\n=================================================================='
    class:
      - name: SUPER_USER
        idleTimeout: 0
        permissions: all
    user:
      - name: ansible
        uid: 2101
        encryptPass: '$5$W9klZ.yt$L19UjdXNi3dRJbTUtCM99qSf2BIOcQzplAnFY6YNWkA'
        permissions: SUPER_USER
  passwordRequirements: minimum-length 8
  services:
    ftp: True
    ssh:
      - max-sessions-per-connection 4
    netconf: True
    rest:
      http:
        port: 8080
      options:
        - enable-explorer
    # dhcp:
    #   group:
    #     name: TRUSTED
    #     iface: ge-0/0/2.0
  ntp:
    bootserver: 10.255.1.1
    server:
      - ipv4_address: 10.255.1.1
      - ipv4_address: 10.255.1.2
